name: CI

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.13.1
          - 4.12.1
          - 4.10.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add . --no-action

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam exec -- dune build @doc

      - name: Deploy to GitHub Pages
        if:  ${{ matrix.os == 'ubuntu-latest' && matrix.ocaml-version == '4.13.1' }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _build/default/_doc/_html/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
